import type { Ally, Disbursement, Municipality, Event, Item } from '../../../types'

export const mockAliados: Ally[] = [
  { id: '1', nombre: 'Fundación Social', nit: '900.123.456-7', contacto: 'Carlos Pérez', email: 'carlos@fsocial.org', telefono: '3001234567', color: '#EAB308', activo: true },
  { id: '2', nombre: 'Corporación Desarrollo', nit: '900.789.012-3', contacto: 'Ana Gómez', email: 'ana@codesarrollo.org', telefono: '3007890123', color: '#3B82F6', activo: true },
  { id: '3', nombre: 'Asociación Cultural', nit: '900.345.678-9', contacto: 'Luis Rojas', email: 'luis@acultural.org', telefono: '3003456789', color: '#22C55E', activo: true },
]

export const mockDesembolsos: Disbursement[] = [
  { id: '1', nombre: 'Desembolso 2025-01', codigo: 'D2025-01', porcentajeParticipacion: 40, vigencia: '2025-01-01', valorReferencia: 500_000_000, activo: true },
  { id: '2', nombre: 'Desembolso 2025-02', codigo: 'D2025-02', porcentajeParticipacion: 35, vigencia: '2025-06-01', valorReferencia: 400_000_000, activo: true },
  { id: '3', nombre: 'Desembolso 2025-03', codigo: 'D2025-03', porcentajeParticipacion: 25, vigencia: '2025-01-01', valorReferencia: 300_000_000, activo: true },
]

export const mockMunicipios: Municipality[] = [
  { id: '1', nombre: 'Bogotá D.C.', departamento: 'Cundinamarca' },
  { id: '2', nombre: 'Medellín', departamento: 'Antioquia' },
  { id: '3', nombre: 'Cali', departamento: 'Valle del Cauca' },
  { id: '4', nombre: 'Barranquilla', departamento: 'Atlántico' },
  { id: '5', nombre: 'Cartagena', departamento: 'Bolívar' },
  { id: '6', nombre: 'Bucaramanga', departamento: 'Santander' },
  { id: '7', nombre: 'Pereira', departamento: 'Risaralda' },
  { id: '8', nombre: 'Manizales', departamento: 'Caldas' },
]

function generateMockItems(eventId: string, count: number): Item[] {
  const categories = ['IVA', 'Consumo', 'Tercero', 'Reembolso'] as const
  const descriptions = [
    'Servicio de logística',
    'Alquiler de equipos',
    'Transporte de materiales',
    'Honorarios profesionales',
    'Material promocional',
    'Alimentación participantes',
  ]

  return Array.from({ length: count }, (_, i) => {
    const cat = categories[i % categories.length]
    const qty = Math.floor(Math.random() * 20) + 1
    const unitVal = (Math.floor(Math.random() * 50) + 5) * 10000
    const base = qty * unitVal
    const iva = cat === 'IVA' ? base * 0.19 : 0
    const impConsumo = cat === 'Consumo' ? base * 0.08 : 0
    const feeTar = (cat === 'IVA' || cat === 'Consumo') ? base * 0.05 : 0
    const feeTer = (cat === 'Tercero' || cat === 'Reembolso') ? base * 0.10 : 0
    const feeTotal = feeTar + feeTer
    const ivaFee = feeTotal * 0.19

    return {
      id: `${eventId}-item-${i + 1}`,
      eventoId: eventId,
      descripcion: descriptions[i % descriptions.length],
      cantidad: qty,
      valorUnitario: unitVal,
      categoriaTributaria: cat,
      aliadoId: undefined,
      base,
      iva,
      impuestoConsumo: impConsumo,
      feeTarifado: feeTar,
      feeTerceros: feeTer,
      ivaFee,
      total: base + iva + impConsumo + feeTotal + ivaFee,
    }
  })
}

export const mockEvents: Event[] = [
  {
    id: 'EVT-001',
    numeroEvento: '2025-001',
    sufijo: 'A',
    responsable: 'María Torres',
    dependencia: 'Secretaría de Cultura',
    fechaEvento: '2025-02-15',
    asistentes: 50,
    dias: 2,
    municipioId: '1',
    vereda: '',
    latitud: 4.7110,
    longitud: -74.0721,
    observaciones: 'Evento de lanzamiento cultural',
    aliadoId: '1',
    desembolsoId: '1',
    esquema: 'cotizacion',
    estado: 'Abierto',
    items: generateMockItems('EVT-001', 3),
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'EVT-002',
    numeroEvento: '2025-002',
    sufijo: 'B',
    responsable: 'Juan García',
    dependencia: 'Secretaría de Educación',
    fechaEvento: '2025-03-20',
    asistentes: 100,
    dias: 3,
    municipioId: '2',
    vereda: '',
    latitud: 6.2476,
    longitud: -75.5658,
    observaciones: 'Taller de capacitación docente',
    aliadoId: '1',
    desembolsoId: '1',
    esquema: 'detalle',
    estado: 'En ejecucion',
    items: generateMockItems('EVT-002', 4),
    createdAt: '2025-02-20T14:30:00Z',
    updatedAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'EVT-003',
    numeroEvento: '2025-003',
    sufijo: '',
    responsable: 'Ana Martínez',
    dependencia: 'Secretaría de Desarrollo',
    fechaEvento: '2025-04-05',
    asistentes: 200,
    dias: 1,
    municipioId: '3',
    vereda: '',
    latitud: 3.4516,
    longitud: -76.5320,
    observaciones: '',
    aliadoId: '2',
    desembolsoId: '2',
    esquema: 'cotizacion',
    estado: 'Ejecutado',
    items: generateMockItems('EVT-003', 5),
    createdAt: '2025-03-05T08:00:00Z',
    updatedAt: '2025-04-20T16:00:00Z',
  },
  {
    id: 'EVT-004',
    numeroEvento: '2025-004',
    sufijo: '',
    responsable: 'Carlos López',
    dependencia: 'Alcaldía Municipal',
    fechaEvento: '2025-05-10',
    asistentes: 30,
    dias: 2,
    municipioId: '5',
    vereda: 'Vereda El Paraíso',
    latitud: 10.3910,
    longitud: -75.5144,
    observaciones: 'Evento comunitario zona rural',
    aliadoId: '3',
    desembolsoId: '3',
    esquema: 'detalle',
    estado: 'Cerrado',
    items: generateMockItems('EVT-004', 2),
    createdAt: '2025-04-10T11:00:00Z',
    updatedAt: '2025-06-01T13:00:00Z',
  },
  {
    id: 'EVT-005',
    numeroEvento: '2025-005',
    sufijo: 'C',
    responsable: 'Laura Sánchez',
    dependencia: 'Secretaría de Cultura',
    fechaEvento: '2025-06-01',
    asistentes: 150,
    dias: 1,
    municipioId: '4',
    vereda: '',
    latitud: 10.9685,
    longitud: -74.7813,
    observaciones: 'Festival cultural',
    aliadoId: '2',
    desembolsoId: '2',
    esquema: 'cotizacion',
    estado: 'Legalizado',
    items: generateMockItems('EVT-005', 6),
    createdAt: '2025-05-01T09:00:00Z',
    updatedAt: '2025-07-15T10:00:00Z',
  },
  {
    id: 'EVT-006',
    numeroEvento: '2025-006',
    sufijo: '',
    responsable: 'Pedro Ramírez',
    dependencia: 'Secretaría de Deportes',
    fechaEvento: '2025-07-10',
    asistentes: 80,
    dias: 2,
    municipioId: '6',
    vereda: '',
    latitud: 7.1253,
    longitud: -73.1198,
    observaciones: '',
    aliadoId: '1',
    desembolsoId: '1',
    esquema: 'detalle',
    estado: 'Abierto',
    items: generateMockItems('EVT-006', 3),
    createdAt: '2025-06-10T07:30:00Z',
    updatedAt: '2025-06-10T07:30:00Z',
  },
  {
    id: 'EVT-007',
    numeroEvento: '2025-007',
    sufijo: 'A',
    responsable: 'Diana Castro',
    dependencia: 'Secretaría de Desarrollo',
    fechaEvento: '2025-08-20',
    asistentes: 60,
    dias: 3,
    municipioId: '7',
    vereda: '',
    latitud: 4.8133,
    longitud: -75.6961,
    observaciones: 'Seminario de desarrollo regional',
    aliadoId: '3',
    desembolsoId: '2',
    esquema: 'cotizacion',
    estado: 'En ejecucion',
    items: generateMockItems('EVT-007', 4),
    createdAt: '2025-06-20T12:00:00Z',
    updatedAt: '2025-07-01T08:00:00Z',
  },
  {
    id: 'EVT-008',
    numeroEvento: '2025-008',
    sufijo: '',
    responsable: 'María Torres',
    dependencia: 'Secretaría de Cultura',
    fechaEvento: '2025-09-05',
    asistentes: 40,
    dias: 1,
    municipioId: '8',
    vereda: '',
    latitud: 5.0700,
    longitud: -75.5173,
    observaciones: 'Taller artístico',
    aliadoId: '1',
    desembolsoId: '1',
    esquema: 'detalle',
    estado: 'Abierto',
    items: generateMockItems('EVT-008', 2),
    createdAt: '2025-07-05T15:00:00Z',
    updatedAt: '2025-07-05T15:00:00Z',
  },
]
